apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJjSEp2WnkxMGFXMWxPbWRwZEdoMVlsOXdZWFJmTVRGQlNsVTJNazFSTUVkdWVrZEhlV05FV0VrNGIxOTZkamxJZVcweFZsSk1URTFoTVV0M1ducEhNblYwUVVWblZGUm5PVFkyVmpsT1VEQlpSWGN6UlZsdlJ6SkJWRkZJVjFscVRWQmlSa2MxVVFvPSIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKCQkiLXgtY2xpLWhpbnRzIjogewoJCQkiZW5hYmxlZCI6ICJ0cnVlIgoJCX0KCX0sCgkiZmVhdHVyZXMiOiB7CgkJImhvb2tzIjogInRydWUiCgl9Cn0=
type: kubernetes.io/dockerconfigjson
