apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJjSEp2WnkxMGFXMWxPbWRwZEdoMVlsOXdZWFJmTVRGQlNsVTJNazFSTUdKSE1GSlVNa042VGt4VlMxOWFiM1ZvVldOTU9FVnROV3RyYTJ4SVJEZEdNWEZLZGxsb1kxQnJOREZPUlhaaVNGQTNRVU5KZUdWS1RVb3pWVWRIVUVGbmRUSm9XbUU0U1FvPSIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKCQkiLXgtY2xpLWhpbnRzIjogewoJCQkiZW5hYmxlZCI6ICJ0cnVlIgoJCX0KCX0sCgkiZmVhdHVyZXMiOiB7CgkJImhvb2tzIjogInRydWUiCgl9Cn0=
type: kubernetes.io/dockerconfigjson
